// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/afs/cern.ch/work/d/demattia/CMSDAS/CMSSW_5_3_3/src/AnalysisMacros/./fullCombination.C";

#endif
