/********************************************************
* /afs/cern.ch/work/d/demattia/CMSDAS/CMSSW_5_3_3/src/AnalysisMacros/fullCombination_C_ACLiC_dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/
#include "/afs/cern.ch/work/d/demattia/CMSDAS/CMSSW_5_3_3/src/AnalysisMacros/fullCombination_C_ACLiC_dict.h" //newlink 3678 

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablefullCombination_C_ACLiC_dict();

extern "C" void G__set_cpp_environmentfullCombination_C_ACLiC_dict() {
  G__add_compiledheader("/tmp/rootcint_xX22t9.h");
