/********************************************************************
* /afs/cern.ch/work/d/demattia/CMSDAS/CMSSW_5_3_3/src/AnalysisMacros/fullCombination_C_ACLiC_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /afs/cern.ch/work/d/demattia/CMSDAS/CMSSW_5_3_3/src/AnalysisMacros/fullCombination_C_ACLiC_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablefullCombination_C_ACLiC_dict();
extern void G__cpp_setup_inheritancefullCombination_C_ACLiC_dict();
extern void G__cpp_setup_typetablefullCombination_C_ACLiC_dict();
extern void G__cpp_setup_memvarfullCombination_C_ACLiC_dict();
extern void G__cpp_setup_globalfullCombination_C_ACLiC_dict();
extern void G__cpp_setup_memfuncfullCombination_C_ACLiC_dict();
extern void G__cpp_setup_funcfullCombination_C_ACLiC_dict();
extern void G__set_cpp_environmentfullCombination_C_ACLiC_dict();
}


#include "/tmp/rootcint_xX22t9.h"
